### PR TITLE
add shell completion and manpage generation

### LINKED ISSUE #61: autocompletions with `clap_complete`
https://github.com/clap-rs/clap/tree/master/clap_complete
i'm working on a PR for this

### PR DESCRIPTION
**Pull request by pauliesnug**
adds shell completion and manpage generation via a command. here's some docs of how to use the commands:
fixes #61 

we can also automatically provide these files for macos, since brew provides a way to auto-install precompiled shell completions and man pages

```bash
# bash
geode completions bash > ~/.local/share/bash-completion/completions/mdbook
# oh-my-zsh
geode completions zsh > ~/.oh-my-zsh/completions/_mdbook
autoload -U compinit && compinit
```

man pages:
Man pages are written in [roff](https://en.wikipedia.org/wiki/Roff_%28software%29). If you have [groff](https://www.gnu.org/software/groff/) installed you can view the man page with `geode generate-manpage | groff -mandoc -Tascii | less`. (or instead of less, add it to your manpage directory). we can also automatically provide the parsed manpage on the repo and then have it installed with  our homebrew tap

### CODE REVIEW

**Comment by pauliesnug** [comment]
this should be ready to merge?

**Comment by pauliesnug** [comment]
@matcool hi, i fixed merge conflicts

**Comment by pauliesnug** [comment]
@matcool why revert dep bump?

**Comment by matcool** [comment]
it and the reformatting of every file (because you changed the formatting rules for some reason) was outside the scope of the pr

**Comment by pauliesnug** [comment]
> it and the reformatting of every file (because you changed the formatting rules for some reason) was outside the scope of the pr

okay ig. the docs i added should be in the docs repo i guess? or maybe just the readme of this repo?

**Pull request merged**
