### PR TITLE
run cargo format and update all deps

### PR DESCRIPTION
**Pull request by TheBearodactyl**
also, i kept `Cargo.lock` this time (even though it's auto-generated every time `cargo build`, `cargo test`, `cargo update`, etc. is run lmao). also, if you want to keep `Cargo.lock`, maybe consider removing it from `.gitignore`

### CODE REVIEW

**Comment by matcool** [comment]
i dont like this, and terrible pr name

**Comment by matcool** [comment]
i feel like all of those updated dependencies is gonna break something, but also running cargo fmt just changes way too much, making this too big of a pr

**Comment by TheBearodactyl** [comment]
i didn't run `cargo fmt`, i used `rustfmt`. also, It being too big of a pr is why i rebased and squashed the commits

**Comment by matcool** [comment]
its still 1400 lines, but also rustfmt is the same thing

**Comment by matcool** [comment]
tests suck

> i didn't run `cargo fmt`, i used `rustfmt`. also, It being too big of a pr is why i rebased and squashed the commits. also, why don't y'all have any tests to make sure it doesn't break? cargo has a builtin test framework

tests suck

**Comment by TheBearodactyl** [comment]
they don't lmao, you've just gotta get the hang of writing them. lemme implement a few real quick

**Comment by matcool** [comment]
can you please not have one big ass pr. either update the dependencies or format the code, not both

**Comment by TheBearodactyl** [comment]
fiiiinee

**Pull request closed without merging**
